management.security.enabled: false
security:
  user.name: admin
  user.password: admin
spring:
  application.name: admin-server
  boot:
    admin:
      url: http://localhost:8087
      turbine:
        clusters: default
        location: turbine
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream